name: Make test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: make
      run: make
